package optic_fusion1.slimefunreloaded.research;

import optic_fusion1.slimefunreloaded.Slimefun;
import optic_fusion1.slimefunreloaded.SlimefunReloaded;
import optic_fusion1.slimefunreloaded.item.SlimefunReloadedItem;
import org.bukkit.NamespacedKey;

public class ResearchRegistery {

  private static final ResearchManager RESEARCH_MANAGER = Slimefun.getResearchManager();
  private static final SlimefunReloaded PLUGIN = Slimefun.getSlimefunReloaded();

  //TODO: Add items
  public void registerResearches() {
    register(new Research(new NamespacedKey(PLUGIN, "Walking Sticks"), 1));
    register(new Research(new NamespacedKey(PLUGIN, "Portalable Crafter"), 1));
    register(new Research(new NamespacedKey(PLUGIN, "Fortune Cookie"), 1));
    register(new Research(new NamespacedKey(PLUGIN, "Portable Dustbin"), 1));
    register(new Research(new NamespacedKey(PLUGIN, "Jerkys"), 2));
    register(new Research(new NamespacedKey(PLUGIN, "Armor Crafting"), 2));
    register(new Research(new NamespacedKey(PLUGIN, "Lumps and Magic"), 3));
    register(new Research(new NamespacedKey(PLUGIN, "Ender Backpack"), 4));
    register(new Research(new NamespacedKey(PLUGIN, "Glowstone Armor"), 3));
    register(new Research(new NamespacedKey(PLUGIN, "Ender Armor"), 4));
    register(new Research(new NamespacedKey(PLUGIN, "Magic Eye of Ender"), 4));
    register(new Research(new NamespacedKey(PLUGIN, "Magic Sugar"), 4));
    register(new Research(new NamespacedKey(PLUGIN, "Monster Jerky"), 5));
    register(new Research(new NamespacedKey(PLUGIN, "Slime Armor"), 5));
    register(new Research(new NamespacedKey(PLUGIN, "Sword of Beheading"), 6));
    register(new Research(new NamespacedKey(PLUGIN, "Electric Work"), 8));
    register(new Research(new NamespacedKey(PLUGIN, "Advanced Electricity"), 9));
    register(new Research(new NamespacedKey(PLUGIN, "Hot Smelting"), 10));
    register(new Research(new NamespacedKey(PLUGIN, "Steel Age"), 11));
    register(new Research(new NamespacedKey(PLUGIN, "Important Power-Related Items"), 12));
    register(new Research(new NamespacedKey(PLUGIN, "Your first Battery"), 10));
    register(new Research(new NamespacedKey(PLUGIN, "Steel Plating"), 14));
    register(new Research(new NamespacedKey(PLUGIN, "Steel Thruster"), 14));
    register(new Research(new NamespacedKey(PLUGIN, "Parachute"), 15));
    register(new Research(new NamespacedKey(PLUGIN, "Grappling Hook"), 15));
    register(new Research(new NamespacedKey(PLUGIN, "Jetpacks"), 22));
    register(new Research(new NamespacedKey(PLUGIN, "Multi Tools"), 18));
    register(new Research(new NamespacedKey(PLUGIN, "Solar Power"), 17));
    register(new Research(new NamespacedKey(PLUGIN, "Elemental Staves"), 17));
    register(new Research(new NamespacedKey(PLUGIN, "Grind Stone"), 4));
    register(new Research(new NamespacedKey(PLUGIN, "Cactus Suit"), 5));
    register(new Research(new NamespacedKey(PLUGIN, "Gold Pan"), 5));
    register(new Research(new NamespacedKey(PLUGIN, "Magical Book Binding"), 5));
    register(new Research(new NamespacedKey(PLUGIN, "New Metals"), 6));
    register(new Research(new NamespacedKey(PLUGIN, "Ore Doubling"), 6));
    register(new Research(new NamespacedKey(PLUGIN, "Bronze Creation"), 8));
    register(new Research(new NamespacedKey(PLUGIN, "Advanced Alloys"), 12));
    register(new Research(new NamespacedKey(PLUGIN, "Carbon Creation"), 9));
    register(new Research(new NamespacedKey(PLUGIN, "Bakery Innovation"), 1));
    register(new Research(new NamespacedKey(PLUGIN, "Gilded Iron Armor"), 16));
    register(new Research(new NamespacedKey(PLUGIN, "Synthetic Diamonds"), 10));
    register(new Research(new NamespacedKey(PLUGIN, "Pressure Chamber"), 14));
    register(new Research(new NamespacedKey(PLUGIN, "Synthetic Sapphires"), 16));
    register(new Research(new NamespacedKey(PLUGIN, "Damascus Steel"), 17));
    register(new Research(new NamespacedKey(PLUGIN, "Damascus Steel Armor"), 18));
    register(new Research(new NamespacedKey(PLUGIN, "Reinforced Alloy"), 22));
    register(new Research(new NamespacedKey(PLUGIN, "Black Diamonds"), 26));
    register(new Research(new NamespacedKey(PLUGIN, "Magic Workbench"), 12));
    register(new Research(new NamespacedKey(PLUGIN, "Wind Staff"), 17));
    register(new Research(new NamespacedKey(PLUGIN, "Reinforced Armor"), 26));
    register(new Research(new NamespacedKey(PLUGIN, "Ore Washer"), 5));
    register(new Research(new NamespacedKey(PLUGIN, "Pure Gold"), 7));
    register(new Research(new NamespacedKey(PLUGIN, "Silicon Valley"), 12));
    register(new Research(new NamespacedKey(PLUGIN, "Fire Staff"), 2));
    register(new Research(new NamespacedKey(PLUGIN, "Smelters Pickaxe"), 17));
    register(new Research(new NamespacedKey(PLUGIN, "Common Talisman"), 14));
    register(new Research(new NamespacedKey(PLUGIN, "Talisman of the Anvil"), 18));
    register(new Research(new NamespacedKey(PLUGIN, "Talisman of the Miner"), 18));
    register(new Research(new NamespacedKey(PLUGIN, "Talisman of the Hunter"), 18));
    register(new Research(new NamespacedKey(PLUGIN, "Talisman of the Lava Walker"), 18));
    register(new Research(new NamespacedKey(PLUGIN, "Talisman of the Water Breather"), 18));
    register(new Research(new NamespacedKey(PLUGIN, "Talisman of the Angel"), 18));
    register(new Research(new NamespacedKey(PLUGIN, "Talisman of the Firefighter"), 18));
    register(new Research(new NamespacedKey(PLUGIN, "Firey Situation"), 14));
    register(new Research(new NamespacedKey(PLUGIN, "Talisman of the Magician"), 20));
    register(new Research(new NamespacedKey(PLUGIN, "Talisman of the Traveller"), 20));
    register(new Research(new NamespacedKey(PLUGIN, "Talisman of the Warrior"), 20));
    register(new Research(new NamespacedKey(PLUGIN, "Talisman of the Knight"), 20));
    register(new Research(new NamespacedKey(PLUGIN, "Shiny Iron"), 11));
    register(new Research(new NamespacedKey(PLUGIN, "Fake Gem"), 17));
    register(new Research(new NamespacedKey(PLUGIN, "Chainmail Armor"), 8));
    register(new Research(new NamespacedKey(PLUGIN, "Talisman of the Whirlwind"), 19));
    register(new Research(new NamespacedKey(PLUGIN, "Talisman of the Wizard"), 22));
    register(new Research(new NamespacedKey(PLUGIN, "Lumber Axe"), 21));
    register(new Research(new NamespacedKey(PLUGIN, "Hazmat Suit"), 21));
    register(new Research(new NamespacedKey(PLUGIN, "Radioactive"), 30));
    register(new Research(new NamespacedKey(PLUGIN, "Ore Purification"), 25));
    register(new Research(new NamespacedKey(PLUGIN, "Redstone Alloy"), 16));
    register(new Research(new NamespacedKey(PLUGIN, "Top Tier Machines"), 24));
    register(new Research(new NamespacedKey(PLUGIN, "First Aid"), 2));
    register(new Research(new NamespacedKey(PLUGIN, "Shiny Armor"), 13));
    register(new Research(new NamespacedKey(PLUGIN, "Night Vision Goggles"), 10));
    register(new Research(new NamespacedKey(PLUGIN, "Pickaxe of Containment"), 14));
    register(new Research(new NamespacedKey(PLUGIN, "Hercules Pickaxe"), 28));
    register(new Research(new NamespacedKey(PLUGIN, "Table Saw"), 4));
    register(new Research(new NamespacedKey(PLUGIN, "Slimy Steel Armor"), 27));
    register(new Research(new NamespacedKey(PLUGIN, "Blade of Vampires"), 26));
    register(new Research(new NamespacedKey(PLUGIN, "Lazy Mining"), 40));
    register(new Research(new NamespacedKey(PLUGIN, "Water Staff"), 8));
    register(new Research(new NamespacedKey(PLUGIN, "Golden City"), 19));
    register(new Research(new NamespacedKey(PLUGIN, "Advanced Mining 101"), 42));
    register(new Research(new NamespacedKey(PLUGIN, "Composting Dirt"), 3));
    register(new Research(new NamespacedKey(PLUGIN, "Farmer Shoes"), 4));
    register(new Research(new NamespacedKey(PLUGIN, "Explosive Tools"), 30));
    register(new Research(new NamespacedKey(PLUGIN, "Automated Gold Pan"), 17));
    register(new Research(new NamespacedKey(PLUGIN, "Boots of the Stomper"), 19));
    register(new Research(new NamespacedKey(PLUGIN, "Pickaxe of the Seeker"), 19));
    register(new Research(new NamespacedKey(PLUGIN, "Backpacks"), 15));
    register(new Research(new NamespacedKey(PLUGIN, "Woven Backpack"), 19));
    register(new Research(new NamespacedKey(PLUGIN, "Cruicible"), 13));
    register(new Research(new NamespacedKey(PLUGIN, "Gilded Backpack"), 22));
    register(new Research(new NamespacedKey(PLUGIN, "Armored Jetpack"), 27));
    register(new Research(new NamespacedKey(PLUGIN, "Ender Talismans"), 28));
    register(new Research(new NamespacedKey(PLUGIN, "Even more Ores"), 10));
    register(new Research(new NamespacedKey(PLUGIN, "Magnetic Metals"), 16));
    register(new Research(new NamespacedKey(PLUGIN, "Infused Magnets"), 18));
    register(new Research(new NamespacedKey(PLUGIN, "Speedy Pickaxe"), 14));
    register(new Research(new NamespacedKey(PLUGIN, "Necromancy"), 19));
    register(new Research(new NamespacedKey(PLUGIN, "Soulbound Storage"), 22));
    register(new Research(new NamespacedKey(PLUGIN, "Jet Boots"), 25));
    register(new Research(new NamespacedKey(PLUGIN, "Armored Jet Boots"), 27));
    register(new Research(new NamespacedKey(PLUGIN, "Seismic Axe"), 29));
    register(new Research(new NamespacedKey(PLUGIN, "Pickaxe of Vein Mining"), 29));
    register(new Research(new NamespacedKey(PLUGIN, "Soulbound Weapons"), 29));
    register(new Research(new NamespacedKey(PLUGIN, "Soulbound Tools"), 29));
    register(new Research(new NamespacedKey(PLUGIN, "Soulbound Armor"), 29));
    register(new Research(new NamespacedKey(PLUGIN, "Soulbound Drinks"), 29));
    register(new Research(new NamespacedKey(PLUGIN, "Soulbound Armor"), 29));
    register(new Research(new NamespacedKey(PLUGIN, "Delicious Drinks"), 29));
    register(new Research(new NamespacedKey(PLUGIN, "Repairing Spawners"), 15));
    register(new Research(new NamespacedKey(PLUGIN, "HO HO HO"), 1));
    register(new Research(new NamespacedKey(PLUGIN, "Enhanced Furnace"), 7));
    register(new Research(new NamespacedKey(PLUGIN, "Better Furnaces"), 18));
    register(new Research(new NamespacedKey(PLUGIN, "High Tier Furnace"), 29));
    register(new Research(new NamespacedKey(PLUGIN, "Reinforced Furnace"), 32));
    register(new Research(new NamespacedKey(PLUGIN, "Carbonado Edged Furnance"), 35));
    register(new Research(new NamespacedKey(PLUGIN, "Heating up"), 32));
    register(new Research(new NamespacedKey(PLUGIN, "Block Placer"), 17));
    register(new Research(new NamespacedKey(PLUGIN, "Lazy Panning"), 29));
    register(new Research(new NamespacedKey(PLUGIN, "Turning things around"), 38));
    register(new Research(new NamespacedKey(PLUGIN, "Robin Hood"), 22));
    register(new Research(new NamespacedKey(PLUGIN, "Sharing with friends"), 30));
    register(new Research(new NamespacedKey(PLUGIN, "XP Storage"), 13));
    register(new Research(new NamespacedKey(PLUGIN, "Withstanding Explosions"), 15));
    register(new Research(new NamespacedKey(PLUGIN, "Happy Easter"), 1));
    register(new Research(new NamespacedKey(PLUGIN, "Golden potion"), 24));
    register(new Research(new NamespacedKey(PLUGIN, "Portable Beverages"), 24));
    register(new Research(new NamespacedKey(PLUGIN, "Ancient Altar"), 15));
    register(new Research(new NamespacedKey(PLUGIN, "Wither-Proof Obsidian"), 21));
    register(new Research(new NamespacedKey(PLUGIN, "Upgraded Solar Cells"), 26));
    register(new Research(new NamespacedKey(PLUGIN, "Elemental Runes"), 15));
    register(new Research(new NamespacedKey(PLUGIN, "Purple Runes"), 18));
    register(new Research(new NamespacedKey(PLUGIN, "Infernal Bonemeal"), 12));
    register(new Research(new NamespacedKey(PLUGIN, "Rainbow Blocks"), 24));
    register(new Research(new NamespacedKey(PLUGIN, "Infused Hopper"), 22));
    register(new Research(new NamespacedKey(PLUGIN, "Wither-Proof Glass"), 20));
    register(new Research(new NamespacedKey(PLUGIN, "Duct Tape"), 14));
    register(new Research(new NamespacedKey(PLUGIN, "Plastic"), 25));
    register(new Research(new NamespacedKey(PLUGIN, "Memory Core"), 28));
    register(new Research(new NamespacedKey(PLUGIN, "Oil"), 30));
    register(new Research(new NamespacedKey(PLUGIN, "Fuel"), 30));
    register(new Research(new NamespacedKey(PLUGIN, "Holograms"), 36));
    register(new Research(new NamespacedKey(PLUGIN, "Tier 1 Capacitors"), 25));
    register(new Research(new NamespacedKey(PLUGIN, "Tier 2 Capacitors"), 32));
    register(new Research(new NamespacedKey(PLUGIN, "Solar Power Plant"), 14));
    register(new Research(new NamespacedKey(PLUGIN, "Powered Furnace"), 15));
    register(new Research(new NamespacedKey(PLUGIN, "Crushing and Grinding"), 20));
    register(new Research(new NamespacedKey(PLUGIN, "Heated Pressure Chamber"), 22));
    register(new Research(new NamespacedKey(PLUGIN, "Coal Generator"), 18));
    register(new Research(new NamespacedKey(PLUGIN, "Bio-Reactor"), 18));
    register(new Research(new NamespacedKey(PLUGIN, "Automatic Enchanting and Disenchanting"), 24));
    register(new Research(new NamespacedKey(PLUGIN, "Automatic Anvil"), 34));
    register(new Research(new NamespacedKey(PLUGIN, "Power Measurement"), 10));
    register(new Research(new NamespacedKey(PLUGIN, "Basic GPS Setup"), 28));
    register(new Research(new NamespacedKey(PLUGIN, "GPS Emergency Waypoint"), 30));
    register(new Research(new NamespacedKey(PLUGIN, "Programmable Androids"), 50));
    register(new Research(new NamespacedKey(PLUGIN, "Android Interfaces"), 26));
    register(new Research(new NamespacedKey(PLUGIN, "GEO-Scans"), 30));
    register(new Research(new NamespacedKey(PLUGIN, "Combustion Reactor"), 38));
    register(new Research(new NamespacedKey(PLUGIN, "Teleporter Base Components"), 42));
    register(new Research(new NamespacedKey(PLUGIN, "Teleporter Activation"), 36));
    register(new Research(new NamespacedKey(PLUGIN, "Upgraded Solar Generators"), 28));
    register(new Research(new NamespacedKey(PLUGIN, "Upgraded Transmitters"), 36));
    register(new Research(new NamespacedKey(PLUGIN, "Elevators"), 28));
    register(new Research(new NamespacedKey(PLUGIN, "Full-Time Solar Power"), 44));
    register(new Research(new NamespacedKey(PLUGIN, "Top Tier Transmitter"), 44));
    register(new Research(new NamespacedKey(PLUGIN, "Energy Networks 101"), 6));
    register(new Research(new NamespacedKey(PLUGIN, "Butcher Androids"), 32));
    register(new Research(new NamespacedKey(PLUGIN, "Organic Food"), 25));
    register(new Research(new NamespacedKey(PLUGIN, "Automated Feeding"), 25));
    register(new Research(new NamespacedKey(PLUGIN, "Advanced Androids"), 60));
    register(new Research(new NamespacedKey(PLUGIN, "Advanced Androids - Butcher"), 30));
    register(new Research(new NamespacedKey(PLUGIN, "Advanced Androids - Fisherman"), 30));
    register(new Research(new NamespacedKey(PLUGIN, "Animal Growth Manipulation"), 32));
    register(new Research(new NamespacedKey(PLUGIN, "Exp Collector"), 36));
    register(new Research(new NamespacedKey(PLUGIN, "Organic Fertilizer"), 36));
    register(new Research(new NamespacedKey(PLUGIN, "Crop Growth Acceleration"), 40));
    register(new Research(new NamespacedKey(PLUGIN, "Upgraded Crop Growth Accelerator"), 44));
    register(new Research(new NamespacedKey(PLUGIN, "Reactor Essentials"), 36));
    register(new Research(new NamespacedKey(PLUGIN, "Nuclear Power Plant"), 48));
    register(new Research(new NamespacedKey(PLUGIN, "Mr Freeze"), 20));
    register(new Research(new NamespacedKey(PLUGIN, "Cargo Basics"), 30));
    register(new Research(new NamespacedKey(PLUGIN, "Cargo Setup"), 30));
    register(new Research(new NamespacedKey(PLUGIN, "Electric Ingot Fabrication"), 18));
    register(new Research(new NamespacedKey(PLUGIN, "Faster Ingot Fabrication"), 26));
    register(new Research(new NamespacedKey(PLUGIN, "Super Fast Ingot Fabrication"), 32));
    register(new Research(new NamespacedKey(PLUGIN, "Automated Crafting"), 20));
    register(new Research(new NamespacedKey(PLUGIN, "Upgraded Food Fabrication"), 28));
    register(new Research(new NamespacedKey(PLUGIN, "Reactor Interaction"), 18));
    register(new Research(new NamespacedKey(PLUGIN, "Fluid Pump"), 28));
    register(new Research(new NamespacedKey(PLUGIN, "Upgraded Freezer"), 29));
    register(new Research(new NamespacedKey(PLUGIN, "Never-Ending Circle"), 30));
    register(new Research(new NamespacedKey(PLUGIN, "Trash"), 8));
    register(new Research(new NamespacedKey(PLUGIN, "Advanced Output Node"), 24));
    register(new Research(new NamespacedKey(PLUGIN, "Carbon Press"), 28));
    register(new Research(new NamespacedKey(PLUGIN, "Electric Smeltery"), 28));
    register(new Research(new NamespacedKey(PLUGIN, "Upgraded Electric Furnace"), 20));
    register(new Research(new NamespacedKey(PLUGIN, "Upgraded Carbon Press"), 26));
    register(new Research(new NamespacedKey(PLUGIN, "Empowered Androids"), 60));
    register(new Research(new NamespacedKey(PLUGIN, "Empowered Androids - Butcher"), 30));
    register(new Research(new NamespacedKey(PLUGIN, "Empowered Androids - Fisherman"), 30));
    register(new Research(new NamespacedKey(PLUGIN, "Ultimate Carbon Press"), 32));
    register(new Research(new NamespacedKey(PLUGIN, "Automated Wither Killer"), 35));
    register(new Research(new NamespacedKey(PLUGIN, "Upgraded Heated Pressure Chamber"), 20));
    register(new Research(new NamespacedKey(PLUGIN, "Elytras"), 20));
    register(new Research(new NamespacedKey(PLUGIN, "Special Elytas"), 30));
    register(new Research(new NamespacedKey(PLUGIN, "Electrified Crucible"), 26));
    register(new Research(new NamespacedKey(PLUGIN, "Hot Crucibles"), 30));
    register(new Research(new NamespacedKey(PLUGIN, "Advanced Electric Smeltery"), 28));
    register(new Research(new NamespacedKey(PLUGIN, "Advanced Androids - Farmer"), 30));
    register(new Research(new NamespacedKey(PLUGIN, "Lava Generator"), 38));
    register(new Research(new NamespacedKey(PLUGIN, "Nether Ice Coolant"), 45));
    register(new Research(new NamespacedKey(PLUGIN, "Nether Star Reactor"), 60));
    register(new Research(new NamespacedKey(PLUGIN, "Blistering Radioactivity"), 38));
    register(new Research(new NamespacedKey(PLUGIN, "Automatic Ignition Chamber"), 12));
    register(new Research(new NamespacedKey(PLUGIN, "Basic machinery output chest"), 20));
    register(new Research(new NamespacedKey(PLUGIN, "Thinned-down Conductivity"), 15));
    register(new Research(new NamespacedKey(PLUGIN, "Radiant Backpack"), 25));
    register(new Research(new NamespacedKey(PLUGIN, "A Dry Day"), 15));
    register(new Research(new NamespacedKey(PLUGIN, "Diet Cookie"), 3));
    register(new Research(new NamespacedKey(PLUGIN, "Storm Staff"), 30));
    register(new Research(new NamespacedKey(PLUGIN, "Soulbound Rune"), 60));
    register(new Research(new NamespacedKey(PLUGIN, "GEO-Miner"), 24));
    register(new Research(new NamespacedKey(PLUGIN, "Lightning Rune"), 24));
    register(new Research(new NamespacedKey(PLUGIN, "Totem of Undying"), 36));
    register(new Research(new NamespacedKey(PLUGIN, "Charging Bench"), 8));
  }

  private void register(Research research, SlimefunReloadedItem... items) {
    RESEARCH_MANAGER.addResearch(research, items);
  }

}
