package optic_fusion1.slimefunreloaded.research;

import optic_fusion1.slimefunreloaded.Slimefun;
import optic_fusion1.slimefunreloaded.SlimefunReloaded;
import optic_fusion1.slimefunreloaded.item.SlimefunReloadedItem;
import org.bukkit.NamespacedKey;

public class ResearchRegistery {

  private static final ResearchManager RESEARCH_MANAGER = Slimefun.getResearchManager();
  private static final SlimefunReloaded PLUGIN = Slimefun.getSlimefunReloaded();

  //TODO: Add items
  public void registerResearches() {
    register(new Research(new NamespacedKey(PLUGIN, "Walking Sticks"), 1));
    register(new Research(new NamespacedKey(PLUGIN, "Portalable Crafter"), 1));
    register(new Research(new NamespacedKey(PLUGIN, "Fortune Cookie"), 1));
    register(new Research(new NamespacedKey(PLUGIN, "Portable Dustbin"), 1));
    register(new Research(new NamespacedKey(PLUGIN, "Jerkys"), 2));
    register(new Research(new NamespacedKey(PLUGIN, "Armor Crafting"), 2));
    register(new Research(new NamespacedKey(PLUGIN, "Lumps and Magic"), 3));
    register(new Research(new NamespacedKey(PLUGIN, "Ender Backpack"), 4));
    register(new Research(new NamespacedKey(PLUGIN, "Glowstone Armor"), 3));
    register(new Research(new NamespacedKey(PLUGIN, "Ender Armor"), 4));
    register(new Research(new NamespacedKey(PLUGIN, "Magic Eye of Ender"), 4));
    register(new Research(new NamespacedKey(PLUGIN, "Magic Sugar"), 4));
    register(new Research(new NamespacedKey(PLUGIN, "Monster Jerky"), 5));
    register(new Research(new NamespacedKey(PLUGIN, "Slime Armor"), 5));
    register(new Research(new NamespacedKey(PLUGIN, "Sword of Beheading"), 6));
    register(new Research(new NamespacedKey(PLUGIN, "Electric Work"), 8));
    register(new Research(new NamespacedKey(PLUGIN, "Advanced Electricity"), 9));
    register(new Research(new NamespacedKey(PLUGIN, "Hot Smelting"), 10));
    register(new Research(new NamespacedKey(PLUGIN, "Steel Age"), 11));
    register(new Research(new NamespacedKey(PLUGIN, "Important Power-Related Items"), 12));
    register(new Research(new NamespacedKey(PLUGIN, "Your first Battery"), 10));
    register(new Research(new NamespacedKey(PLUGIN, "Steel Plating"), 14));
    register(new Research(new NamespacedKey(PLUGIN, "Steel Thruster"), 14));
    register(new Research(new NamespacedKey(PLUGIN, "Parachute"), 15));
    register(new Research(new NamespacedKey(PLUGIN, "Grappling Hook"), 15));
    register(new Research(new NamespacedKey(PLUGIN, "Jetpacks"), 22));
    register(new Research(new NamespacedKey(PLUGIN, "Multi Tools"), 18));
    register(new Research(new NamespacedKey(PLUGIN, "Solar Power"), 17));
    register(new Research(new NamespacedKey(PLUGIN, "Elemental Staves"), 17));
    register(new Research(new NamespacedKey(PLUGIN, "Grind Stone"), 4));
    register(new Research(new NamespacedKey(PLUGIN, "Cactus Suit"), 5));
    register(new Research(new NamespacedKey(PLUGIN, "Gold Pan"), 5));
    register(new Research(new NamespacedKey(PLUGIN, "Magical Book Binding"), 5));
    register(new Research(new NamespacedKey(PLUGIN, "New Metals"), 6));
    register(new Research(new NamespacedKey(PLUGIN, "Ore Doubling"), 6));
    register(new Research(new NamespacedKey(PLUGIN, "Bronze Creation"), 8));
    register(new Research(new NamespacedKey(PLUGIN, "Advanced Alloys"), 12));
    register(new Research(new NamespacedKey(PLUGIN, "Carbon Creation"), 9));
    register(new Research(new NamespacedKey(PLUGIN, "Bakery Innovation"), 1));
    register(new Research(new NamespacedKey(PLUGIN, "Gilded Iron Armor"), 16));
    register(new Research(new NamespacedKey(PLUGIN, "Synthetic Diamonds"), 10));
    register(new Research(new NamespacedKey(PLUGIN, "Pressure Chamber"), 14));
    register(new Research(new NamespacedKey(PLUGIN, "Synthetic Sapphires"), 16));
    register(new Research(new NamespacedKey(PLUGIN, "Damascus Steel"), 17));
    register(new Research(new NamespacedKey(PLUGIN, "Damascus Steel Armor"), 18));
    register(new Research(new NamespacedKey(PLUGIN, "Reinforced Alloy"), 22));
    register(new Research(new NamespacedKey(PLUGIN, "Black Diamonds"), 26));
    register(new Research(new NamespacedKey(PLUGIN, "Magic Workbench"), 12));
    register(new Research(new NamespacedKey(PLUGIN, "Wind Staff"), 17));
    register(new Research(new NamespacedKey(PLUGIN, "Reinforced Armor"), 26));
    register(new Research(new NamespacedKey(PLUGIN, "Ore Washer"), 5));
    register(new Research(new NamespacedKey(PLUGIN, "Pure Gold"), 7));
    register(new Research(new NamespacedKey(PLUGIN, "Silicon Valley"), 12));
    register(new Research(new NamespacedKey(PLUGIN, "Fire Staff"), 2));
    register(new Research(new NamespacedKey(PLUGIN, "Smelters Pickaxe"), 17));
    register(new Research(new NamespacedKey(PLUGIN, "Common Talisman"), 14));
    register(new Research(new NamespacedKey(PLUGIN, "Talisman of the Anvil"), 18));
    register(new Research(new NamespacedKey(PLUGIN, "Talisman of the Miner"), 18));
    register(new Research(new NamespacedKey(PLUGIN, "Talisman of the Hunter"), 18));
    register(new Research(new NamespacedKey(PLUGIN, "Talisman of the Lava Walker"), 18));
    register(new Research(new NamespacedKey(PLUGIN, "Talisman of the Water Breather"), 18));
    register(new Research(new NamespacedKey(PLUGIN, "Talisman of the Angel"), 18));
    register(new Research(new NamespacedKey(PLUGIN, "Talisman of the Firefighter"), 18));
    register(new Research(new NamespacedKey(PLUGIN, "Firey Situation"), 14));
    register(new Research(new NamespacedKey(PLUGIN, "Talisman of the Magician"), 20));
    register(new Research(new NamespacedKey(PLUGIN, "Talisman of the Traveller"), 20));
    register(new Research(new NamespacedKey(PLUGIN, "Talisman of the Warrior"), 20));
    register(new Research(new NamespacedKey(PLUGIN, "Talisman of the Knight"), 20));
    register(new Research(new NamespacedKey(PLUGIN, "Shiny Iron"), 11));
    register(new Research(new NamespacedKey(PLUGIN, "Fake Gem"), 17));
    register(new Research(new NamespacedKey(PLUGIN, "Chainmail Armor"), 8));
    register(new Research(new NamespacedKey(PLUGIN, "Talisman of the Whirlwind"), 19));
    register(new Research(new NamespacedKey(PLUGIN, "Talisman of the Wizard"), 22));
    register(new Research(new NamespacedKey(PLUGIN, "Lumber Axe"), 21));
    register(new Research(new NamespacedKey(PLUGIN, "Hazmat Suit"), 21));
    register(new Research(new NamespacedKey(PLUGIN, "Radioactive"), 30));
    register(new Research(new NamespacedKey(PLUGIN, "Ore Purification"), 25));
    register(new Research(new NamespacedKey(PLUGIN, "Redstone Alloy"), 16));
    register(new Research(new NamespacedKey(PLUGIN, "Top Tier Machines"), 24));
    register(new Research(new NamespacedKey(PLUGIN, "First Aid"), 2));
    register(new Research(new NamespacedKey(PLUGIN, "Shiny Armor"), 13));
    register(new Research(new NamespacedKey(PLUGIN, "Night Vision Goggles"), 10));
    register(new Research(new NamespacedKey(PLUGIN, "Pickaxe of Containment"), 14));
    register(new Research(new NamespacedKey(PLUGIN, "Hercules Pickaxe"), 28));
    register(new Research(new NamespacedKey(PLUGIN, "Table Saw"), 4));
    register(new Research(new NamespacedKey(PLUGIN, "Slimy Steel Armor"), 27));
    register(new Research(new NamespacedKey(PLUGIN, "Blade of Vampires"), 26));
    register(new Research(new NamespacedKey(PLUGIN, "Lazy Mining"), 40));
    register(new Research(new NamespacedKey(PLUGIN, "Water Staff"), 8));
    register(new Research(new NamespacedKey(PLUGIN, "Golden City"), 19));
    register(new Research(new NamespacedKey(PLUGIN, "Advanced Mining 101"), 42));
    register(new Research(new NamespacedKey(PLUGIN, "Composting Dirt"), 3));
    register(new Research(new NamespacedKey(PLUGIN, "Farmer Shoes"), 4));
    register(new Research(new NamespacedKey(PLUGIN, "Explosive Tools"), 30));
    register(new Research(new NamespacedKey(PLUGIN, "Automated Gold Pan"), 17));
    register(new Research(new NamespacedKey(PLUGIN, "Boots of the Stomper"), 19));
    register(new Research(new NamespacedKey(PLUGIN, "Pickaxe of the Seeker"), 19));
    register(new Research(new NamespacedKey(PLUGIN, "Backpacks"), 15));
    register(new Research(new NamespacedKey(PLUGIN, "Woven Backpack"), 19));
    register(new Research(new NamespacedKey(PLUGIN, "Cruicible"), 13));
    register(new Research(new NamespacedKey(PLUGIN, "Gilded Backpack"), 22));
    register(new Research(new NamespacedKey(PLUGIN, "Armored Jetpack"), 27));
    register(new Research(new NamespacedKey(PLUGIN, "Ender Talismans"), 28));
    register(new Research(new NamespacedKey(PLUGIN, "Even more Ores"), 10));
    register(new Research(new NamespacedKey(PLUGIN, "Magnetic Metals"), 16));
    register(new Research(new NamespacedKey(PLUGIN, "Infused Magnets"), 18));
    register(new Research(new NamespacedKey(PLUGIN, "Speedy Pickaxe"), 14));
    register(new Research(new NamespacedKey(PLUGIN, "Necromancy"), 19));
    register(new Research(new NamespacedKey(PLUGIN, "Soulbound Storage"), 22));
    register(new Research(new NamespacedKey(PLUGIN, "Jet Boots"), 25));
    register(new Research(new NamespacedKey(PLUGIN, "Armored Jet Boots"), 27));
    register(new Research(new NamespacedKey(PLUGIN, "Seismic Axe"), 29));
    register(new Research(new NamespacedKey(PLUGIN, "Pickaxe of Vein Mining"), 29));
    register(new Research(new NamespacedKey(PLUGIN, "Soulbound Weapons"), 29));
    register(new Research(new NamespacedKey(PLUGIN, "Soulbound Tools"), 29));
    register(new Research(new NamespacedKey(PLUGIN, "Soulbound Armor"), 29));
    register(new Research(new NamespacedKey(PLUGIN, "Soulbound Drinks"), 29));
    register(new Research(new NamespacedKey(PLUGIN, "Soulbound Armor"), 29));
    register(new Research(new NamespacedKey(PLUGIN, "Delicious Drinks"), 29));
    register(new Research(new NamespacedKey(PLUGIN, "Repairing Spawners"), 15));
    register(new Research(new NamespacedKey(PLUGIN, "HO HO HO"), 1));
    register(new Research(new NamespacedKey(PLUGIN, "Enhanced Furnace"), 7));
    register(new Research(new NamespacedKey(PLUGIN, "Better Furnaces"), 18));
    register(new Research(new NamespacedKey(PLUGIN, "High Tier Furnace"), 29));
    register(new Research(new NamespacedKey(PLUGIN, "Reinforced Furnace"), 32));
    register(new Research(new NamespacedKey(PLUGIN, "Carbonado Edged Furnance"), 35));
    register(new Research(new NamespacedKey(PLUGIN, "Heating up"), 32));
    register(new Research(new NamespacedKey(PLUGIN, "Block Placer"), 17));
    register(new Research(new NamespacedKey(PLUGIN, "Lazy Panning"), 29));
    register(new Research(new NamespacedKey(PLUGIN, "Turning things around"), 38));
    register(new Research(new NamespacedKey(PLUGIN, "Robin Hood"), 22));
    register(new Research(new NamespacedKey(PLUGIN, "Sharing with friends"), 30));
    register(new Research(new NamespacedKey(PLUGIN, "XP Storage"), 13));
    register(new Research(new NamespacedKey(PLUGIN, "Withstanding Explosions"), 15));
    register(new Research(new NamespacedKey(PLUGIN, "Happy Easter"), 1));
    register(new Research(new NamespacedKey(PLUGIN, "Golden potion"), 24));
    register(new Research(new NamespacedKey(PLUGIN, "Portable Beverages"), 24));
    register(new Research(new NamespacedKey(PLUGIN, "Ancient Altar"), 15));
    register(new Research(new NamespacedKey(PLUGIN, "Wither-Proof Obsidian"), 21));
    register(new Research(new NamespacedKey(PLUGIN, "Upgraded Solar Cells"), 26));
    register(new Research(new NamespacedKey(PLUGIN, "Elemental Runes"), 15));
    register(new Research(new NamespacedKey(PLUGIN, "Purple Runes"), 18));
    register(new Research(new NamespacedKey(PLUGIN, "Infernal Bonemeal"), 12));
    register(new Research(new NamespacedKey(PLUGIN, "Rainbow Blocks"), 24));
    register(new Research(new NamespacedKey(PLUGIN, "Infused Hopper"), 22));
    register(new Research(new NamespacedKey(PLUGIN, "Wither-Proof Glass"), 20));
    register(new Research(new NamespacedKey(PLUGIN, "Duct Tape"), 14));
    register(new Research(new NamespacedKey(PLUGIN, "Plastic"), 25));
    register(new Research(new NamespacedKey(PLUGIN, "Memory Core"), 28));
    register(new Research(new NamespacedKey(PLUGIN, "Oil"), 30));
    register(new Research(new NamespacedKey(PLUGIN, "Fuel"), 30));
    register(new Research(new NamespacedKey(PLUGIN, "Holograms"), 36));
    register(new Research(new NamespacedKey(PLUGIN, "Tier 1 Capacitors"), 25));
    register(new Research(new NamespacedKey(PLUGIN, "Tier 2 Capacitors"), 32));
    register(new Research(new NamespacedKey(PLUGIN, "Solar Power Plant"), 14));
    /*
	    Slimefun.registerResearch(new Research(170, "Powered Furnace", 15), SlimefunItems.ELECTRIC_FURNACE);
	    Slimefun.registerResearch(new Research(171, "Crushing and Grinding", 20), SlimefunItems.ELECTRIC_ORE_GRINDER, SlimefunItems.ELECTRIC_INGOT_PULVERIZER);
	    Slimefun.registerResearch(new Research(172, "Heated Pressure Chamber", 22), SlimefunItems.HEATED_PRESSURE_CHAMBER);
	    Slimefun.registerResearch(new Research(173, "Coal Generator", 18), SlimefunItems.COAL_GENERATOR);
	    Slimefun.registerResearch(new Research(173, "Bio-Reactor", 18), SlimefunItems.BIO_REACTOR);
	    Slimefun.registerResearch(new Research(174, "Automatic Enchanting and Disenchanting", 24), SlimefunItems.AUTO_ENCHANTER, SlimefunItems.AUTO_DISENCHANTER);
	    Slimefun.registerResearch(new Research(175, "Automatic Anvil", 34), SlimefunItems.AUTO_ANVIL, SlimefunItems.AUTO_ANVIL_2);
	    Slimefun.registerResearch(new Research(176, "Power Measurement", 10), SlimefunItems.MULTIMETER);
	    Slimefun.registerResearch(new Research(177, "Basic GPS Setup", 28), SlimefunItems.GPS_TRANSMITTER, SlimefunItems.GPS_CONTROL_PANEL, SlimefunItems.GPS_MARKER_TOOL);
	    Slimefun.registerResearch(new Research(178, "GPS Emergency Waypoint", 30), SlimefunItems.GPS_EMERGENCY_TRANSMITTER);
	    Slimefun.registerResearch(new Research(179, "Programmable Androids", 50), SlimefunItems.PROGRAMMABLE_ANDROID, SlimefunItems.PROGRAMMABLE_ANDROID_FARMER, SlimefunItems.PROGRAMMABLE_ANDROID_BUTCHER, SlimefunItems.PROGRAMMABLE_ANDROID_FISHERMAN, SlimefunItems.PROGRAMMABLE_ANDROID_MINER, SlimefunItems.PROGRAMMABLE_ANDROID_WOODCUTTER);
	    Slimefun.registerResearch(new Research(180, "Android Interfaces", 26), SlimefunItems.ANDROID_INTERFACE_FUEL, SlimefunItems.ANDROID_INTERFACE_ITEMS);
	    Slimefun.registerResearch(new Research(181, "GEO-Scans", 30), SlimefunItems.GPS_GEO_SCANNER, SlimefunItems.PORTABLE_GEO_SCANNER);
	    Slimefun.registerResearch(new Research(182, "Combustion Reactor", 38), SlimefunItems.COMBUSTION_REACTOR);
	    Slimefun.registerResearch(new Research(183, "Teleporter Base Components", 42), SlimefunItems.GPS_TELEPORTATION_MATRIX, SlimefunItems.GPS_TELEPORTER_PYLON);
	    Slimefun.registerResearch(new Research(184, "Teleporter Activation", 36), SlimefunItems.GPS_ACTIVATION_DEVICE_PERSONAL, SlimefunItems.GPS_ACTIVATION_DEVICE_SHARED);
	    Slimefun.registerResearch(new Research(185, "Upgraded Solar Generators", 28), SlimefunItems.SOLAR_GENERATOR_2, SlimefunItems.SOLAR_GENERATOR_3);
	    Slimefun.registerResearch(new Research(186, "Upgraded Transmitters", 36), SlimefunItems.GPS_TRANSMITTER_2, SlimefunItems.GPS_TRANSMITTER_3);
	    Slimefun.registerResearch(new Research(187, "Elevators", 28), SlimefunItems.ELEVATOR);
	    Slimefun.registerResearch(new Research(188, "Full-Time Solar Power", 44), SlimefunItems.SOLAR_GENERATOR_4);
	    Slimefun.registerResearch(new Research(189, "Top Tier Transmitter", 44), SlimefunItems.GPS_TRANSMITTER_4);
	    Slimefun.registerResearch(new Research(190, "Energy Networks 101", 6), SlimefunItems.ENERGY_REGULATOR);
	    Slimefun.registerResearch(new Research(191, "Butcher Androids", 32), SlimefunItems.PROGRAMMABLE_ANDROID_BUTCHER);
	    Slimefun.registerResearch(new Research(192, "Organic Food", 25), SlimefunItems.FOOD_FABRICATOR, SlimefunItems.WHEAT_ORGANIC_FOOD, SlimefunItems.CARROT_ORGANIC_FOOD, SlimefunItems.POTATO_ORGANIC_FOOD, SlimefunItems.SEEDS_ORGANIC_FOOD, SlimefunItems.BEETROOT_ORGANIC_FOOD, SlimefunItems.MELON_ORGANIC_FOOD, SlimefunItems.APPLE_ORGANIC_FOOD, SlimefunItems.SWEET_BERRIES_ORGANIC_FOOD);
	    Slimefun.registerResearch(new Research(193, "Automated Feeding", 25), SlimefunItems.AUTO_BREEDER);
	    Slimefun.registerResearch(new Research(194, "Advanced Androids", 60), SlimefunItems.PROGRAMMABLE_ANDROID_2);
	    Slimefun.registerResearch(new Research(195, "Advanced Androids - Butcher", 30), SlimefunItems.PROGRAMMABLE_ANDROID_2_BUTCHER);
	    Slimefun.registerResearch(new Research(196, "Advanced Androids - Fisherman", 30), SlimefunItems.PROGRAMMABLE_ANDROID_2_FISHERMAN);
	    Slimefun.registerResearch(new Research(197, "Animal Growth Manipulation", 32), SlimefunItems.ANIMAL_GROWTH_ACCELERATOR);
	    Slimefun.registerResearch(new Research(198, "Exp Collector", 36), SlimefunItems.XP_COLLECTOR);
	    Slimefun.registerResearch(new Research(199, "Organic Fertilizer", 36), SlimefunItems.FOOD_COMPOSTER, SlimefunItems.WHEAT_FERTILIZER, SlimefunItems.CARROT_FERTILIZER, SlimefunItems.POTATO_FERTILIZER, SlimefunItems.SEEDS_FERTILIZER, SlimefunItems.BEETROOT_FERTILIZER, SlimefunItems.MELON_FERTILIZER, SlimefunItems.APPLE_FERTILIZER, SlimefunItems.SWEET_BERRIES_FERTILIZER);
	    Slimefun.registerResearch(new Research(200, "Crop Growth Acceleration", 40), SlimefunItems.CROP_GROWTH_ACCELERATOR);
	    Slimefun.registerResearch(new Research(201, "Upgraded Crop Growth Accelerator", 44), SlimefunItems.CROP_GROWTH_ACCELERATOR_2);
	    Slimefun.registerResearch(new Research(202, "Reactor Essentials", 36), SlimefunItems.REACTOR_COOLANT_CELL, SlimefunItems.NEPTUNIUM, SlimefunItems.PLUTONIUM);
	    Slimefun.registerResearch(new Research(203, "Nuclear Power Plant", 48), SlimefunItems.NUCLEAR_REACTOR);
	    Slimefun.registerResearch(new Research(204, "Mr Freeze", 20), SlimefunItems.FREEZER);
	    Slimefun.registerResearch(new Research(205, "Cargo Basics", 30), SlimefunItems.CARGO_MOTOR, SlimefunItems.CARGO_MANAGER, SlimefunItems.CARGO_NODE);
	    Slimefun.registerResearch(new Research(206, "Cargo Setup", 30), SlimefunItems.CARGO_INPUT, SlimefunItems.CARGO_OUTPUT);
	    Slimefun.registerResearch(new Research(207, "Electric Ingot Fabrication", 18), SlimefunItems.ELECTRIC_GOLD_PAN, SlimefunItems.ELECTRIC_DUST_WASHER, SlimefunItems.ELECTRIC_INGOT_FACTORY);
	    Slimefun.registerResearch(new Research(208, "Faster Ingot Fabrication", 26), SlimefunItems.ELECTRIC_GOLD_PAN_2, SlimefunItems.ELECTRIC_DUST_WASHER_2, SlimefunItems.ELECTRIC_INGOT_FACTORY_2);
	    Slimefun.registerResearch(new Research(209, "Super Fast Ingot Fabrication", 32), SlimefunItems.ELECTRIC_GOLD_PAN_3, SlimefunItems.ELECTRIC_DUST_WASHER_3, SlimefunItems.ELECTRIC_INGOT_FACTORY_3, SlimefunItems.ELECTRIC_ORE_GRINDER_2);
	    Slimefun.registerResearch(new Research(210, "Automated Crafting", 20), SlimefunItems.AUTOMATED_CRAFTING_CHAMBER);
	    Slimefun.registerResearch(new Research(211, "Upgraded Food Fabrication", 28), SlimefunItems.FOOD_FABRICATOR_2, SlimefunItems.FOOD_COMPOSTER_2);
	    Slimefun.registerResearch(new Research(212, "Reactor Interaction", 18), SlimefunItems.REACTOR_ACCESS_PORT);
	    Slimefun.registerResearch(new Research(213, "Fluid Pump", 28), SlimefunItems.FLUID_PUMP);
	    Slimefun.registerResearch(new Research(214, "Upgraded Freezer", 29), SlimefunItems.FREEZER_2);
	    Slimefun.registerResearch(new Research(215, "Never-Ending Circle", 30), SlimefunItems.BOOSTED_URANIUM);
	    Slimefun.registerResearch(new Research(216, "Trash", 8), SlimefunItems.TRASH_CAN);
	    Slimefun.registerResearch(new Research(217, "Advanced Output Node", 24), SlimefunItems.CARGO_OUTPUT_ADVANCED);
	    Slimefun.registerResearch(new Research(218, "Carbon Press", 28), SlimefunItems.CARBON_PRESS);
	    Slimefun.registerResearch(new Research(219, "Electric Smeltery", 28), SlimefunItems.ELECTRIC_SMELTERY);
	    Slimefun.registerResearch(new Research(220, "Upgraded Electric Furnace", 20), SlimefunItems.ELECTRIC_FURNACE_2, SlimefunItems.ELECTRIC_FURNACE_3);
	    Slimefun.registerResearch(new Research(221, "Upgraded Carbon Press", 26), SlimefunItems.CARBON_PRESS_2);
	    Slimefun.registerResearch(new Research(222, "Empowered Androids", 60), SlimefunItems.PROGRAMMABLE_ANDROID_3);
	    Slimefun.registerResearch(new Research(223, "Empowered Androids - Butcher", 30), SlimefunItems.PROGRAMMABLE_ANDROID_3_BUTCHER);
	    Slimefun.registerResearch(new Research(224, "Empowered Androids - Fisherman", 30), SlimefunItems.PROGRAMMABLE_ANDROID_3_FISHERMAN);
	    Slimefun.registerResearch(new Research(225, "Ultimate Carbon Press", 32), SlimefunItems.CARBON_PRESS_3);
	    Slimefun.registerResearch(new Research(226, "Automated Wither Killer", 35), SlimefunItems.WITHER_ASSEMBLER);
	    Slimefun.registerResearch(new Research(227, "Upgraded Heated Pressure Chamber", 20), SlimefunItems.HEATED_PRESSURE_CHAMBER_2);
	    Slimefun.registerResearch(new Research(228, "Elytras", 20), SlimefunItems.ELYTRA_SCALE, SlimefunItems.ELYTRA);
	    Slimefun.registerResearch(new Research(229, "Special Elytras", 30), SlimefunItems.INFUSED_ELYTRA, SlimefunItems.SOULBOUND_ELYTRA);
	    Slimefun.registerResearch(new Research(230, "Electrified Crucible", 26), SlimefunItems.ELECTRIFIED_CRUCIBLE);
	    Slimefun.registerResearch(new Research(231, "Hot Crucibles", 30), SlimefunItems.ELECTRIFIED_CRUCIBLE_2, SlimefunItems.ELECTRIFIED_CRUCIBLE_3);
	    Slimefun.registerResearch(new Research(232, "Advanced Electric Smeltery", 28), SlimefunItems.ELECTRIC_SMELTERY_2);
	    Slimefun.registerResearch(new Research(233, "Advanced Androids - Farmer", 30), SlimefunItems.PROGRAMMABLE_ANDROID_2_FARMER);
	    Slimefun.registerResearch(new Research(234, "Lava Generator", 38), SlimefunItems.LAVA_GENERATOR);
	    Slimefun.registerResearch(new Research(235, "Nether Ice Coolant", 45), SlimefunItems.NETHER_ICE, SlimefunItems.ENRICHED_NETHER_ICE, SlimefunItems.NETHER_ICE_COOLANT_CELL, SlimefunItems.NETHER_DRILL);
	    Slimefun.registerResearch(new Research(236, "Nether Star Reactor", 60), SlimefunItems.NETHERSTAR_REACTOR);
	    Slimefun.registerResearch(new Research(237, "Blistering Radioactivity", 38), SlimefunItems.BLISTERING_INGOT, SlimefunItems.BLISTERING_INGOT_2, SlimefunItems.BLISTERING_INGOT_3);
	    Slimefun.registerResearch(new Research(239, "Automatic Ignition Chamber", 12), SlimefunItems.IGNITION_CHAMBER);
	    Slimefun.registerResearch(new Research(240, "Basic machinery output chest", 20), SlimefunItems.OUTPUT_CHEST);
	    Slimefun.registerResearch(new Research(241, "Thinned-down Conductivity", 15), SlimefunItems.COPPER_WIRE);
	    Slimefun.registerResearch(new Research(242, "Radiant Backpack", 25), SlimefunItems.RADIANT_BACKPACK);
	    Slimefun.registerResearch(new Research(243, "A Dry Day", 15), SlimefunItems.AUTO_DRIER);
	    Slimefun.registerResearch(new Research(244, "Diet Cookie", 3), SlimefunItems.DIET_COOKIE);
	    Slimefun.registerResearch(new Research(245, "Storm Staff", 30), SlimefunItems.STAFF_STORM);
	    Slimefun.registerResearch(new Research(246, "Soulbound Rune", 60), SlimefunItems.RUNE_SOULBOUND);
	    Slimefun.registerResearch(new Research(247, "GEO-Miner", 24), SlimefunItems.GEO_MINER);
	    Slimefun.registerResearch(new Research(248, "Lightning Rune", 24), SlimefunItems.RUNE_LIGHTNING);
	    Slimefun.registerResearch(new Research(249, "Totem of Undying", 36), SlimefunItems.TOTEM_OF_UNDYING);
          Slimefun.registerResearch(new Research(250, "Charging Bench", 8), SlimefunItems.CHARGING_BENCH);
     */
  }

  private void register(Research research, SlimefunReloadedItem... items) {
    RESEARCH_MANAGER.addResearch(research, items);
  }

}
